#!/bin/bash

### BEGIN INIT INFO
# Provides:             duckpan-update
# Required-Start:       $remote_fs $network
# Required-Stop:        $remote_fs $network
# Default-Start:        3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Update DuckPAN
# Description:          Update DuckPAN at boot so that the DuckDuckHack VM user
#                       does not have to do so manually
### END INIT INFO

PATH=/usr/bin/:/bin:/sbin

INSTALL_PATH=/home/vagrant/perl5/bin/duckpan
LOG_PATH=/var/log/boot.log

# Often during DuckDuckHack VM development, you commented out the lines in the
# DuckPAN cookbook in order to speed up your testing of the VM. If so, this
# script should exit cleanly.
function exit_not_installed(){
echo "DuckPAN is not installed or the installation path is no longer"
echo "${INSTALL_PATH}"
echo "Exiting duckpan-update"
initctl emit --no-wait duckpan-updated
exit 0
}
function exit_failed_to_download(){
echo "Failed to download"
echo "Exiting duckpan-update"
initctl emit --no-wait duckpan-updated
exit 0
}
function exit_failed_to_run(){
echo "Failed to run update script"
echo "Exiting duckpan-update"
initctl emit --no-wait duckpan-updated
exit 0
}


case "$1" in
	start)
		echo 'Updating DuckPAN (init script "duckpan-update")'
		echo "This could take several minutes, or longer if your machine is slow"
		echo "or there is a large update to install."
		echo "Output will be logged to ${LOG_PATH}"
#		test -f ${INSTALL_PATH} || exit_not_installed

		echo "Attempting to download http://duckpan.com/install.pl as duckpan-install.pl"
		su -l vagrant -c 'wget -L http://duckpan.com/install.pl -O duckpan-install.pl' || exit_failed_to_download
		echo "duckpan-install.pl downloaded successfully. Running it now."
		su -l vagrant -c 'bash -l -i -c "perl duckpan-install.pl"' || exit_failed_to_run
		echo "DuckPAN was updated successfully or there was no update to install."

		# /etc/init/lightdm.override makes LightDM wait for this signal for 2 reasons:
		# 1. The user really shouldn't start using the VM until DuckPAN has been
		#    updated.
		# 2. There seems to be a bug whereby boot logging (to /var/log/boot.log) does
		#    not occur while LightDM/X.org is starting. This only happens when the
		#    VirtualBox Guest Additions are in use. It usually interferes with this
		#    init script's logging, as well as other init scripts too.
		initctl emit --no-wait duckpan-updated
		;;
	stop)
		# Do nothing during shutdown
		;;
	*)
		echo "Usage: $0 {start}"
		;;
esac

exit 0
